"""
models/intent_contract.py — Pydantic model for the structured JSON produced
by the Intent Contract Generator (LLM call per requirement).

This schema is passed to the Code Tracer, Test Generator, and Report Builder.
"""

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field

# Import here to avoid circular imports; CodeRegion is defined in a sibling module.
from models.code_region import CodeRegion


class EvidenceStrategy(str, Enum):
    unit_test = "unit_test"
    static_analysis = "static_analysis"
    both = "both"
    unknown = "unknown"


class IntentContract(BaseModel):
    """Structured specification generated by the LLM for a single requirement."""

    requirement_id: str = Field(
        ..., description="Identifier matching the source Requirement (e.g. 'R01')"
    )
    summary: str = Field(
        ..., description="Short human-readable label for this requirement"
    )
    acceptance_criteria: List[str] = Field(
        default_factory=list,
        description="Ordered list of verifiable criteria that must hold",
    )
    evidence_strategy: EvidenceStrategy = Field(
        default=EvidenceStrategy.unit_test,
        description="Preferred verification approach",
    )
    keywords: List[str] = Field(
        default_factory=list,
        description="Search tokens for the Code Tracer to locate relevant code",
    )
    test_hint: str = Field(
        default="",
        description="Hint for the Test Generator about what to assert",
    )


class Requirement(BaseModel):
    """A single parsed requirement from the input text."""

    id: str = Field(..., description="Assigned identifier, e.g. 'R01'")
    raw_text: str = Field(..., description="Original requirement text as supplied")


class RequirementResult(BaseModel):
    """Final per-requirement output from the full verification pipeline."""

    id: str
    raw: str
    contract: IntentContract | None = None
    traced_code: List[CodeRegion] = Field(default_factory=list)
    generated_test: str = ""
    execution_output: str = ""
    verdict: str = "UNPROVEN"          # PROVEN | FAILED | UNPROVEN
    evidence_summary: str = ""
    error: str = ""
